# Generated by Django 4.0.3 on 2022-04-17 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carsuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nationality', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('total_cars', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(upload_to='profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
