# Generated by Django 4.0.3 on 2022-04-03 16:44

import cars.web_cars.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Ensure this value contains only letters and numbers')])),
                ('car_model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Ensure this value contains only letters and numbers')])),
                ('type', models.CharField(choices=[('sedan', 'sedan'), ('hatchback', 'hatchback'), ('convertable', 'convertable'), ('sport car', 'sport car'), ('estate', 'estate'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('Other', 'Other')], max_length=30)),
                ('engine', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('EV', 'EV'), ('hybrid', 'hybrid')], max_length=30)),
                ('hp', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('auto', 'auto')], max_length=30)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[cars.web_cars.validators.MaxFileSizeInMbValidator(10)])),
                ('mileage', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nationality', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('total_cars', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
