# Generated by Django 4.0.3 on 2022-04-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_cars.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
    ]
