# Generated by Django 4.0.3 on 2022-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('car_brand', 'car_model')},
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[(None, 'Choose Engine Type'), ('petrol', 'petrol'), ('diesel', 'diesel'), ('EV', 'EV'), ('hybrid', 'hybrid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[(None, 'Choose Transmission Type'), ('manual', 'manual'), ('auto', 'auto')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[(None, 'Choose Car Type'), ('sedan', 'sedan'), ('hatchback', 'hatchback'), ('convertable', 'convertable'), ('sport car', 'sport car'), ('estate', 'estate'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('Other', 'Other')], max_length=30),
        ),
    ]
