# Generated by Django 4.0.3 on 2022-04-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0009_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user_profile',
        ),
    ]
