# Generated by Django 4.0.3 on 2022-04-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0011_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
