# Generated by Django 4.0.3 on 2022-04-23 14:32

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0012_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Ensure this value contains only letters and numbers')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Ensure this value contains only letters and numbers')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
