# Generated by Django 4.0.3 on 2022-04-26 22:00

import cars.web_cars.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_cars', '0013_alter_car_car_brand_alter_car_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('^[0-9a-zA-Z- ]*$', 'Ensure this value contains only letters, numbers and -')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z- ]*$', 'Ensure this value contains only letters, numbers and -')]),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='photos', validators=[cars.web_cars.validators.MaxFileSizeInMbValidator(10)])),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_cars.car')),
            ],
        ),
    ]
